<?php

namespace Omnipay\Telcell\Message;

use Omnipay\Telcell\Gateway;
use Omnipay\Common\Message\AbstractResponse;

/**
 * Class CompletePurchaseResponse
 * @package Omnipay\Telcell\Message
 */
class CompletePurchaseResponse extends AbstractResponse
{
    /**
     * Indicates whether transaction was successful
     * @return bool
     */
    public function isSuccessful()
    {
        return !empty($this->data['status']) && $this->data['status'] === Gateway::TRANSACTION_STATUS_PAID;
    }

    /**
     * Get transaction ID, generated by merchant
     * @return mixed|string
     */
    public function getTransactionId()
    {
        return array_get($this->data, 'payment_id');
    }

    /**
     * Get transaction reference, generated by gateway
     * @return mixed|null|string
     */
    public function getTransactionReference()
    {
        return array_get($this->data, 'invoice');
    }
}